### ISSUE TITLE
Haiku OS port TODO

### ISSUE THREAD

**Issue by rollerozxa** [Bithack/principia#146]
An initial Haiku OS port exists in the `haiku-port` branch. It is mostly functional, but here are some things that are yet to be done with it:

- [ ] URL handler
- [ ] Ability to send commands to an already running instance of Principia (for playing community levels, see how the Linux backend does it with Unix pipes)
- [ ] Fix crash when quickadd dialog is closed
- [ ] Packaging for inclusion in Haiku's repositories

Not everything needs to be fixed before it can be merged into `master`.
