### ISSUE TITLE
Initial FOSS release roadmap (1.5.2)

### ISSUE THREAD

**Issue by rollerozxa** [Bithack/principia#64]
Getting an initial stable FOSS release of Principia out there should be a high priority, as I believe it would be the best way to drum up more activity and attention to get the ball rolling.

So I propose that the first open source version should be a rather minor one, like 1.5.2. With the minor patch version comes a limited scope, which should hopefully make it be released in a more timely manner.

**What's to be done:**
- [X] Make previously unused objects available in the sandbox menu
- [X] Update Android version to target a newer API, along with fixing any issues that come with that
	- [X] Scoped app data
		- [x] Write info about accessing and backing up this storage on the Wiki (it can tend to be hard to access and fragile, best to inform players about keeping their data safe) (@rollerozxa)
	- [x] Fix sandbox menu being harder to use now due to fullscreen mode being enabled
- [X] Remove license verification on all platforms
- [x] Make cURL library buildable from available source code on Android (required for F-Droid) (@rollerozxa)
- [x] Another batch of object help text updates imported from the new Wiki (@rollerozxa)
- [x] Fix release versions of Linux freezing randomly for unknown reasons (#43)
- [x] Resolve GTK styling once and for all...
	- For Linux it should always use system's styling, on Windows release versions it should use the custom styling (debug versions break in spectacular fashion)

For a full list of what's done there's the [Changelog](https://principia-web.se/wiki/Changelog) page on the Wiki which I've just started and will be keeping up to date with new changes.

Outside of this any bugfixes and other improvements are welcome independent of the roadmap, but I think new features that would warrant a new level version or the like should wait. Please voice any suggestions or additions.

**Releasing/packaging-related things:**
- [x] Increment the version number all over the place (Android manifest, Windows installer/resource file, main menu version number, version code...)
- [X] Arch packaging (AUR)
	- [x] Make a new `principia` AUR package that tracks stable releases (@rollerozxa)
- [x] AppImage packaging
	- Would be really nice to have as it would be distro-agnostic, it should also prompt the user asking if they want the protocol link .desktop installed into ~/.local/share/applications/ to make community site links work properly
- [ ] Ubuntu PPA (it will automatically build for all recent versions of Ubuntu right? good stuff.)
- [X] Improve Windows installer with stuff from the old 1.5.2 installer
	- (Hm... Should it uninstall the old version before installing a new version? Things like the cURL mod might remain in the program folder instead and cause issues)
- Android:
	- [ ] Play Store!
	- [x] Submit Principia for inclusion in F-Droid (requires cURL be buildable from source) (@rollerozxa)

**Comment by rollerozxa** [comment]
Fixing puzzles should definitively be part of 1.5.2 I think...

**Comment by rollerozxa** [comment]
As it is right now I see 1.5.2 as a rolling release beta version. New builds will be made when new changes have been merged and master is considered stable enough. 

If/when 1.5.2 stable releases, we *need* to be ready to hype it up. We should have a new trailer ready and spread the word such that FOSS news sites would want to cover it, because it will be our chance to make a great first impression on people.

**Comment by Mailaender** [comment]
I was about to submit a package to @flathub and complain about the lack of tagged releases until I saw this.

**Comment by Prophet1980** [comment]
I'd really like to see more misc objects added, similar to the logic gates, new electronics, robotics, actual content, sure, bug fixes, and updates, are great, but, not if we're left with the same functionality at the end of the day, as a user, long time owner, purchaser, etc, I've been dreaming about new content for years, is, all I'm saying, anyways, I really appreciate you bringing this project back to life, it's great to see new releases.

P.S. Think about exposing the mechanisms for users to add objects via external files, ie, expose internal functions for a scripting language, some sort of format .xml(etc) for describing the objects, etc, that way if you ever stop developing the app, we can more easily create new content still.

**Comment by griffi-gh** [comment]
@Prophet1980 this release is more about getting game stable so we can release it, but if you want any specific features implemented, feel free to open an issue!

**Comment by Prophet1980** [comment]
> @Prophet1980 this release is more about getting game stable so we can release it, but if you want any specific features implemented, feel free to open an issue!

Well, I appreciate the quick response, but, really, my edit explains it clearly, though if you would like to see that have it's own issue for posterity, then, sure not a problem.

Anyways, thank you very much for all your hard work, I've done a lot of development myself over the years, and, I know it can be a thankless task sometimes. 😁

**Comment by Prophet1980** [comment]
<quote>I don't think the game is flexible enough to support modding properly, but I'm pretty sure it can be done to some degree! (e.g. as objects use dynamic dispatch), and it's actually one of the things i want to try implementing sometime later.</quote>-- End Quote 

Having done similar through reverse engineering, it's gotta at least be easier working from source code, than from ASM, memory editing, etc, but, I haven't looked at the existing code base, so, perhaps not, but, hey inspirationally speaking, when us devs are motivated to make something happen, nothing can usually stop us, including lack of source code. 😜

**Comment by rollerozxa** [comment]
> P.S. Think about exposing the mechanisms for users to add objects via external files, ie, expose internal functions for a scripting language, some sort of format .xml(etc) for describing the objects, etc, that way if you ever stop developing the app, we can more easily create new content still.

I'm unsure what this would entail. The game is open source now, so anyone can extend it however way they see fit, any kind of "modding" functionality in the traditional sense that would be implemented would pale in comparison to just hacking on the source code.

I would however like to see the Lua scripting functionality to be extended and made more powerful, along with being able to morph a LuaScript object into any model of your choosing and selection of input/output sockets to go along with it effectively creating completely custom circuitry objects scriptable using Lua.

**Comment by Prophet1980** [comment]
Well, unfortunately, my PC made a loud pop sound, and hasn't booted since, I'm working from my phone these days, and, AIDE made some development possible, even it's not been working correctly recently, so, until I get around to repairing my PC, or more likely building a new one.

**Comment by griffi-gh** [comment]
> any kind of "modding" functionality in the traditional sense that would be implemented would pale in comparison to just hacking on the source code.

And that's to be expected;  
It just needs to be "good enough".

**Comment by Prophet1980** [comment]
> > any kind of "modding" functionality in the traditional sense that would be implemented would pale in comparison to just hacking on the source code.
> 
> And that's to be expected....; It just needs to be "good enough".

Exactly, I'm glad you are on the same wavelength, seems this project is in good hands. 👍

**Comment by rollerozxa** [comment]
https://principia-web.se/news/13
